// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	Initialize
	GetFeatures
	Features
	ClearSession
	ApplySettings
	ChangePin
	Ping
	Success
	Failure
	ButtonRequest
	ButtonAck
	PinMatrixRequest
	PinMatrixAck
	Cancel
	PassphraseRequest
	PassphraseAck
	GetEntropy
	Entropy
	GetPublicKey
	PublicKey
	GetAddress
	Address
	WipeDevice
	LoadDevice
	ResetDevice
	EntropyRequest
	EntropyAck
	RecoveryDevice
	WordRequest
	WordAck
	SignMessage
	VerifyMessage
	MessageSignature
	EncryptMessage
	EncryptedMessage
	DecryptMessage
	DecryptedMessage
	CipherKeyValue
	CipheredKeyValue
	EstimateTxSize
	TxSize
	SignTx
	SimpleSignTx
	TxRequest
	TxAck
	SignIdentity
	SignedIdentity
	FirmwareErase
	FirmwareUpload
	DebugLinkDecision
	DebugLinkGetState
	DebugLinkState
	DebugLinkStop
	DebugLinkLog
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/conejoninja/trezor/pb/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// *
// Mapping between Trezor wire identifier (uint) and a protobuf message
type MessageType int32

const (
	MessageType_MessageType_Initialize        MessageType = 0
	MessageType_MessageType_Ping              MessageType = 1
	MessageType_MessageType_Success           MessageType = 2
	MessageType_MessageType_Failure           MessageType = 3
	MessageType_MessageType_ChangePin         MessageType = 4
	MessageType_MessageType_WipeDevice        MessageType = 5
	MessageType_MessageType_FirmwareErase     MessageType = 6
	MessageType_MessageType_FirmwareUpload    MessageType = 7
	MessageType_MessageType_GetEntropy        MessageType = 9
	MessageType_MessageType_Entropy           MessageType = 10
	MessageType_MessageType_GetPublicKey      MessageType = 11
	MessageType_MessageType_PublicKey         MessageType = 12
	MessageType_MessageType_LoadDevice        MessageType = 13
	MessageType_MessageType_ResetDevice       MessageType = 14
	MessageType_MessageType_SignTx            MessageType = 15
	MessageType_MessageType_SimpleSignTx      MessageType = 16
	MessageType_MessageType_Features          MessageType = 17
	MessageType_MessageType_PinMatrixRequest  MessageType = 18
	MessageType_MessageType_PinMatrixAck      MessageType = 19
	MessageType_MessageType_Cancel            MessageType = 20
	MessageType_MessageType_TxRequest         MessageType = 21
	MessageType_MessageType_TxAck             MessageType = 22
	MessageType_MessageType_CipherKeyValue    MessageType = 23
	MessageType_MessageType_ClearSession      MessageType = 24
	MessageType_MessageType_ApplySettings     MessageType = 25
	MessageType_MessageType_ButtonRequest     MessageType = 26
	MessageType_MessageType_ButtonAck         MessageType = 27
	MessageType_MessageType_GetAddress        MessageType = 29
	MessageType_MessageType_Address           MessageType = 30
	MessageType_MessageType_EntropyRequest    MessageType = 35
	MessageType_MessageType_EntropyAck        MessageType = 36
	MessageType_MessageType_SignMessage       MessageType = 38
	MessageType_MessageType_VerifyMessage     MessageType = 39
	MessageType_MessageType_MessageSignature  MessageType = 40
	MessageType_MessageType_PassphraseRequest MessageType = 41
	MessageType_MessageType_PassphraseAck     MessageType = 42
	MessageType_MessageType_EstimateTxSize    MessageType = 43
	MessageType_MessageType_TxSize            MessageType = 44
	MessageType_MessageType_RecoveryDevice    MessageType = 45
	MessageType_MessageType_WordRequest       MessageType = 46
	MessageType_MessageType_WordAck           MessageType = 47
	MessageType_MessageType_CipheredKeyValue  MessageType = 48
	MessageType_MessageType_EncryptMessage    MessageType = 49
	MessageType_MessageType_EncryptedMessage  MessageType = 50
	MessageType_MessageType_DecryptMessage    MessageType = 51
	MessageType_MessageType_DecryptedMessage  MessageType = 52
	MessageType_MessageType_SignIdentity      MessageType = 53
	MessageType_MessageType_SignedIdentity    MessageType = 54
	MessageType_MessageType_GetFeatures       MessageType = 55
	MessageType_MessageType_DebugLinkDecision MessageType = 100
	MessageType_MessageType_DebugLinkGetState MessageType = 101
	MessageType_MessageType_DebugLinkState    MessageType = 102
	MessageType_MessageType_DebugLinkStop     MessageType = 103
	MessageType_MessageType_DebugLinkLog      MessageType = 104
)

var MessageType_name = map[int32]string{
	0:   "MessageType_Initialize",
	1:   "MessageType_Ping",
	2:   "MessageType_Success",
	3:   "MessageType_Failure",
	4:   "MessageType_ChangePin",
	5:   "MessageType_WipeDevice",
	6:   "MessageType_FirmwareErase",
	7:   "MessageType_FirmwareUpload",
	9:   "MessageType_GetEntropy",
	10:  "MessageType_Entropy",
	11:  "MessageType_GetPublicKey",
	12:  "MessageType_PublicKey",
	13:  "MessageType_LoadDevice",
	14:  "MessageType_ResetDevice",
	15:  "MessageType_SignTx",
	16:  "MessageType_SimpleSignTx",
	17:  "MessageType_Features",
	18:  "MessageType_PinMatrixRequest",
	19:  "MessageType_PinMatrixAck",
	20:  "MessageType_Cancel",
	21:  "MessageType_TxRequest",
	22:  "MessageType_TxAck",
	23:  "MessageType_CipherKeyValue",
	24:  "MessageType_ClearSession",
	25:  "MessageType_ApplySettings",
	26:  "MessageType_ButtonRequest",
	27:  "MessageType_ButtonAck",
	29:  "MessageType_GetAddress",
	30:  "MessageType_Address",
	35:  "MessageType_EntropyRequest",
	36:  "MessageType_EntropyAck",
	38:  "MessageType_SignMessage",
	39:  "MessageType_VerifyMessage",
	40:  "MessageType_MessageSignature",
	41:  "MessageType_PassphraseRequest",
	42:  "MessageType_PassphraseAck",
	43:  "MessageType_EstimateTxSize",
	44:  "MessageType_TxSize",
	45:  "MessageType_RecoveryDevice",
	46:  "MessageType_WordRequest",
	47:  "MessageType_WordAck",
	48:  "MessageType_CipheredKeyValue",
	49:  "MessageType_EncryptMessage",
	50:  "MessageType_EncryptedMessage",
	51:  "MessageType_DecryptMessage",
	52:  "MessageType_DecryptedMessage",
	53:  "MessageType_SignIdentity",
	54:  "MessageType_SignedIdentity",
	55:  "MessageType_GetFeatures",
	100: "MessageType_DebugLinkDecision",
	101: "MessageType_DebugLinkGetState",
	102: "MessageType_DebugLinkState",
	103: "MessageType_DebugLinkStop",
	104: "MessageType_DebugLinkLog",
}
var MessageType_value = map[string]int32{
	"MessageType_Initialize":        0,
	"MessageType_Ping":              1,
	"MessageType_Success":           2,
	"MessageType_Failure":           3,
	"MessageType_ChangePin":         4,
	"MessageType_WipeDevice":        5,
	"MessageType_FirmwareErase":     6,
	"MessageType_FirmwareUpload":    7,
	"MessageType_GetEntropy":        9,
	"MessageType_Entropy":           10,
	"MessageType_GetPublicKey":      11,
	"MessageType_PublicKey":         12,
	"MessageType_LoadDevice":        13,
	"MessageType_ResetDevice":       14,
	"MessageType_SignTx":            15,
	"MessageType_SimpleSignTx":      16,
	"MessageType_Features":          17,
	"MessageType_PinMatrixRequest":  18,
	"MessageType_PinMatrixAck":      19,
	"MessageType_Cancel":            20,
	"MessageType_TxRequest":         21,
	"MessageType_TxAck":             22,
	"MessageType_CipherKeyValue":    23,
	"MessageType_ClearSession":      24,
	"MessageType_ApplySettings":     25,
	"MessageType_ButtonRequest":     26,
	"MessageType_ButtonAck":         27,
	"MessageType_GetAddress":        29,
	"MessageType_Address":           30,
	"MessageType_EntropyRequest":    35,
	"MessageType_EntropyAck":        36,
	"MessageType_SignMessage":       38,
	"MessageType_VerifyMessage":     39,
	"MessageType_MessageSignature":  40,
	"MessageType_PassphraseRequest": 41,
	"MessageType_PassphraseAck":     42,
	"MessageType_EstimateTxSize":    43,
	"MessageType_TxSize":            44,
	"MessageType_RecoveryDevice":    45,
	"MessageType_WordRequest":       46,
	"MessageType_WordAck":           47,
	"MessageType_CipheredKeyValue":  48,
	"MessageType_EncryptMessage":    49,
	"MessageType_EncryptedMessage":  50,
	"MessageType_DecryptMessage":    51,
	"MessageType_DecryptedMessage":  52,
	"MessageType_SignIdentity":      53,
	"MessageType_SignedIdentity":    54,
	"MessageType_GetFeatures":       55,
	"MessageType_DebugLinkDecision": 100,
	"MessageType_DebugLinkGetState": 101,
	"MessageType_DebugLinkState":    102,
	"MessageType_DebugLinkStop":     103,
	"MessageType_DebugLinkLog":      104,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Request: Reset device to default state and ask for device details
// @next Features
type Initialize struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Initialize) Reset()                    { *m = Initialize{} }
func (m *Initialize) String() string            { return proto.CompactTextString(m) }
func (*Initialize) ProtoMessage()               {}
func (*Initialize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// Request: Ask for device details (no device reset)
// @next Features
type GetFeatures struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetFeatures) Reset()                    { *m = GetFeatures{} }
func (m *GetFeatures) String() string            { return proto.CompactTextString(m) }
func (*GetFeatures) ProtoMessage()               {}
func (*GetFeatures) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// Response: Reports various information about the device
// @prev Initialize
// @prev GetFeatures
type Features struct {
	Vendor               *string           `protobuf:"bytes,1,opt,name=vendor" json:"vendor,omitempty"`
	MajorVersion         *uint32           `protobuf:"varint,2,opt,name=major_version,json=majorVersion" json:"major_version,omitempty"`
	MinorVersion         *uint32           `protobuf:"varint,3,opt,name=minor_version,json=minorVersion" json:"minor_version,omitempty"`
	PatchVersion         *uint32           `protobuf:"varint,4,opt,name=patch_version,json=patchVersion" json:"patch_version,omitempty"`
	BootloaderMode       *bool             `protobuf:"varint,5,opt,name=bootloader_mode,json=bootloaderMode" json:"bootloader_mode,omitempty"`
	DeviceId             *string           `protobuf:"bytes,6,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	PinProtection        *bool             `protobuf:"varint,7,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	PassphraseProtection *bool             `protobuf:"varint,8,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	Language             *string           `protobuf:"bytes,9,opt,name=language" json:"language,omitempty"`
	Label                *string           `protobuf:"bytes,10,opt,name=label" json:"label,omitempty"`
	Coins                []*types.CoinType `protobuf:"bytes,11,rep,name=coins" json:"coins,omitempty"`
	Initialized          *bool             `protobuf:"varint,12,opt,name=initialized" json:"initialized,omitempty"`
	Revision             []byte            `protobuf:"bytes,13,opt,name=revision" json:"revision,omitempty"`
	BootloaderHash       []byte            `protobuf:"bytes,14,opt,name=bootloader_hash,json=bootloaderHash" json:"bootloader_hash,omitempty"`
	Imported             *bool             `protobuf:"varint,15,opt,name=imported" json:"imported,omitempty"`
	PinCached            *bool             `protobuf:"varint,16,opt,name=pin_cached,json=pinCached" json:"pin_cached,omitempty"`
	PassphraseCached     *bool             `protobuf:"varint,17,opt,name=passphrase_cached,json=passphraseCached" json:"passphrase_cached,omitempty"`
	XXX_unrecognized     []byte            `json:"-"`
}

func (m *Features) Reset()                    { *m = Features{} }
func (m *Features) String() string            { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()               {}
func (*Features) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Features) GetVendor() string {
	if m != nil && m.Vendor != nil {
		return *m.Vendor
	}
	return ""
}

func (m *Features) GetMajorVersion() uint32 {
	if m != nil && m.MajorVersion != nil {
		return *m.MajorVersion
	}
	return 0
}

func (m *Features) GetMinorVersion() uint32 {
	if m != nil && m.MinorVersion != nil {
		return *m.MinorVersion
	}
	return 0
}

func (m *Features) GetPatchVersion() uint32 {
	if m != nil && m.PatchVersion != nil {
		return *m.PatchVersion
	}
	return 0
}

func (m *Features) GetBootloaderMode() bool {
	if m != nil && m.BootloaderMode != nil {
		return *m.BootloaderMode
	}
	return false
}

func (m *Features) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Features) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *Features) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *Features) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *Features) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Features) GetCoins() []*types.CoinType {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *Features) GetInitialized() bool {
	if m != nil && m.Initialized != nil {
		return *m.Initialized
	}
	return false
}

func (m *Features) GetRevision() []byte {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *Features) GetBootloaderHash() []byte {
	if m != nil {
		return m.BootloaderHash
	}
	return nil
}

func (m *Features) GetImported() bool {
	if m != nil && m.Imported != nil {
		return *m.Imported
	}
	return false
}

func (m *Features) GetPinCached() bool {
	if m != nil && m.PinCached != nil {
		return *m.PinCached
	}
	return false
}

func (m *Features) GetPassphraseCached() bool {
	if m != nil && m.PassphraseCached != nil {
		return *m.PassphraseCached
	}
	return false
}

// *
// Request: clear session (removes cached PIN, passphrase, etc).
// @next Success
type ClearSession struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClearSession) Reset()                    { *m = ClearSession{} }
func (m *ClearSession) String() string            { return proto.CompactTextString(m) }
func (*ClearSession) ProtoMessage()               {}
func (*ClearSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// *
// Request: change language and/or label of the device
// @next Success
// @next Failure
// @next ButtonRequest
// @next PinMatrixRequest
type ApplySettings struct {
	Language         *string `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Label            *string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	UsePassphrase    *bool   `protobuf:"varint,3,opt,name=use_passphrase,json=usePassphrase" json:"use_passphrase,omitempty"`
	Homescreen       []byte  `protobuf:"bytes,4,opt,name=homescreen" json:"homescreen,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApplySettings) Reset()                    { *m = ApplySettings{} }
func (m *ApplySettings) String() string            { return proto.CompactTextString(m) }
func (*ApplySettings) ProtoMessage()               {}
func (*ApplySettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApplySettings) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *ApplySettings) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *ApplySettings) GetUsePassphrase() bool {
	if m != nil && m.UsePassphrase != nil {
		return *m.UsePassphrase
	}
	return false
}

func (m *ApplySettings) GetHomescreen() []byte {
	if m != nil {
		return m.Homescreen
	}
	return nil
}

// *
// Request: Starts workflow for setting/changing/removing the PIN
// @next ButtonRequest
// @next PinMatrixRequest
type ChangePin struct {
	Remove           *bool  `protobuf:"varint,1,opt,name=remove" json:"remove,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChangePin) Reset()                    { *m = ChangePin{} }
func (m *ChangePin) String() string            { return proto.CompactTextString(m) }
func (*ChangePin) ProtoMessage()               {}
func (*ChangePin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChangePin) GetRemove() bool {
	if m != nil && m.Remove != nil {
		return *m.Remove
	}
	return false
}

// *
// Request: Test if the device is alive, device sends back the message in Success response
// @next Success
type Ping struct {
	Message              *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	ButtonProtection     *bool   `protobuf:"varint,2,opt,name=button_protection,json=buttonProtection" json:"button_protection,omitempty"`
	PinProtection        *bool   `protobuf:"varint,3,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	PassphraseProtection *bool   `protobuf:"varint,4,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Ping) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Ping) GetButtonProtection() bool {
	if m != nil && m.ButtonProtection != nil {
		return *m.ButtonProtection
	}
	return false
}

func (m *Ping) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *Ping) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

// *
// Response: Success of the previous request
type Success struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Success) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Response: Failure of the previous request
type Failure struct {
	Code             *types.FailureType `protobuf:"varint,1,opt,name=code,enum=FailureType" json:"code,omitempty"`
	Message          *string            `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Failure) Reset()                    { *m = Failure{} }
func (m *Failure) String() string            { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()               {}
func (*Failure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Failure) GetCode() types.FailureType {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return types.FailureType_Failure_UnexpectedMessage
}

func (m *Failure) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// *
// Response: Device is waiting for HW button press.
// @next ButtonAck
// @next Cancel
type ButtonRequest struct {
	Code             *types.ButtonRequestType `protobuf:"varint,1,opt,name=code,enum=ButtonRequestType" json:"code,omitempty"`
	Data             *string                  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ButtonRequest) Reset()                    { *m = ButtonRequest{} }
func (m *ButtonRequest) String() string            { return proto.CompactTextString(m) }
func (*ButtonRequest) ProtoMessage()               {}
func (*ButtonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ButtonRequest) GetCode() types.ButtonRequestType {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return types.ButtonRequestType_ButtonRequest_Other
}

func (m *ButtonRequest) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// *
// Request: Computer agrees to wait for HW button press
// @prev ButtonRequest
type ButtonAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ButtonAck) Reset()                    { *m = ButtonAck{} }
func (m *ButtonAck) String() string            { return proto.CompactTextString(m) }
func (*ButtonAck) ProtoMessage()               {}
func (*ButtonAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// *
// Response: Device is asking computer to show PIN matrix and awaits PIN encoded using this matrix scheme
// @next PinMatrixAck
// @next Cancel
type PinMatrixRequest struct {
	Type             *types.PinMatrixRequestType `protobuf:"varint,1,opt,name=type,enum=PinMatrixRequestType" json:"type,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PinMatrixRequest) Reset()                    { *m = PinMatrixRequest{} }
func (m *PinMatrixRequest) String() string            { return proto.CompactTextString(m) }
func (*PinMatrixRequest) ProtoMessage()               {}
func (*PinMatrixRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PinMatrixRequest) GetType() types.PinMatrixRequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return types.PinMatrixRequestType_PinMatrixRequestType_Current
}

// *
// Request: Computer responds with encoded PIN
// @prev PinMatrixRequest
type PinMatrixAck struct {
	Pin              *string `protobuf:"bytes,1,req,name=pin" json:"pin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PinMatrixAck) Reset()                    { *m = PinMatrixAck{} }
func (m *PinMatrixAck) String() string            { return proto.CompactTextString(m) }
func (*PinMatrixAck) ProtoMessage()               {}
func (*PinMatrixAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PinMatrixAck) GetPin() string {
	if m != nil && m.Pin != nil {
		return *m.Pin
	}
	return ""
}

// *
// Request: Abort last operation that required user interaction
// @prev ButtonRequest
// @prev PinMatrixRequest
// @prev PassphraseRequest
type Cancel struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Cancel) Reset()                    { *m = Cancel{} }
func (m *Cancel) String() string            { return proto.CompactTextString(m) }
func (*Cancel) ProtoMessage()               {}
func (*Cancel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// *
// Response: Device awaits encryption passphrase
// @next PassphraseAck
// @next Cancel
type PassphraseRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PassphraseRequest) Reset()                    { *m = PassphraseRequest{} }
func (m *PassphraseRequest) String() string            { return proto.CompactTextString(m) }
func (*PassphraseRequest) ProtoMessage()               {}
func (*PassphraseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// *
// Request: Send passphrase back
// @prev PassphraseRequest
type PassphraseAck struct {
	Passphrase       *string `protobuf:"bytes,1,req,name=passphrase" json:"passphrase,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PassphraseAck) Reset()                    { *m = PassphraseAck{} }
func (m *PassphraseAck) String() string            { return proto.CompactTextString(m) }
func (*PassphraseAck) ProtoMessage()               {}
func (*PassphraseAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PassphraseAck) GetPassphrase() string {
	if m != nil && m.Passphrase != nil {
		return *m.Passphrase
	}
	return ""
}

// *
// Request: Request a sample of random data generated by hardware RNG. May be used for testing.
// @next ButtonRequest
// @next Entropy
// @next Failure
type GetEntropy struct {
	Size             *uint32 `protobuf:"varint,1,req,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetEntropy) Reset()                    { *m = GetEntropy{} }
func (m *GetEntropy) String() string            { return proto.CompactTextString(m) }
func (*GetEntropy) ProtoMessage()               {}
func (*GetEntropy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetEntropy) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

// *
// Response: Reply with random data generated by internal RNG
// @prev GetEntropy
type Entropy struct {
	Entropy          []byte `protobuf:"bytes,1,req,name=entropy" json:"entropy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Entropy) Reset()                    { *m = Entropy{} }
func (m *Entropy) String() string            { return proto.CompactTextString(m) }
func (*Entropy) ProtoMessage()               {}
func (*Entropy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Entropy) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

// *
// Request: Ask device for public key corresponding to address_n path
// @next PassphraseRequest
// @next PublicKey
// @next Failure
type GetPublicKey struct {
	AddressN         []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	EcdsaCurveName   *string  `protobuf:"bytes,2,opt,name=ecdsa_curve_name,json=ecdsaCurveName" json:"ecdsa_curve_name,omitempty"`
	ShowDisplay      *bool    `protobuf:"varint,3,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetPublicKey) Reset()                    { *m = GetPublicKey{} }
func (m *GetPublicKey) String() string            { return proto.CompactTextString(m) }
func (*GetPublicKey) ProtoMessage()               {}
func (*GetPublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetPublicKey) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *GetPublicKey) GetEcdsaCurveName() string {
	if m != nil && m.EcdsaCurveName != nil {
		return *m.EcdsaCurveName
	}
	return ""
}

func (m *GetPublicKey) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

// *
// Response: Contains public key derived from device private seed
// @prev GetPublicKey
type PublicKey struct {
	Node             *types.HDNodeType `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	Xpub             *string           `protobuf:"bytes,2,opt,name=xpub" json:"xpub,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PublicKey) Reset()                    { *m = PublicKey{} }
func (m *PublicKey) String() string            { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()               {}
func (*PublicKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PublicKey) GetNode() *types.HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *PublicKey) GetXpub() string {
	if m != nil && m.Xpub != nil {
		return *m.Xpub
	}
	return ""
}

// *
// Request: Ask device for address corresponding to address_n path
// @next PassphraseRequest
// @next Address
// @next Failure
type GetAddress struct {
	AddressN         []uint32                        `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	CoinName         *string                         `protobuf:"bytes,2,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	ShowDisplay      *bool                           `protobuf:"varint,3,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	Multisig         *types.MultisigRedeemScriptType `protobuf:"bytes,4,opt,name=multisig" json:"multisig,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *GetAddress) Reset()                    { *m = GetAddress{} }
func (m *GetAddress) String() string            { return proto.CompactTextString(m) }
func (*GetAddress) ProtoMessage()               {}
func (*GetAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

const Default_GetAddress_CoinName string = "Bitcoin"

func (m *GetAddress) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *GetAddress) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_GetAddress_CoinName
}

func (m *GetAddress) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

func (m *GetAddress) GetMultisig() *types.MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

// *
// Response: Contains address derived from device private seed
// @prev GetAddress
type Address struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Address) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

// *
// Request: Request device to wipe all sensitive data and settings
// @next ButtonRequest
type WipeDevice struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *WipeDevice) Reset()                    { *m = WipeDevice{} }
func (m *WipeDevice) String() string            { return proto.CompactTextString(m) }
func (*WipeDevice) ProtoMessage()               {}
func (*WipeDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

// *
// Request: Load seed and related internal settings from the computer
// @next ButtonRequest
// @next Success
// @next Failure
type LoadDevice struct {
	Mnemonic             *string           `protobuf:"bytes,1,opt,name=mnemonic" json:"mnemonic,omitempty"`
	Node                 *types.HDNodeType `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
	Pin                  *string           `protobuf:"bytes,3,opt,name=pin" json:"pin,omitempty"`
	PassphraseProtection *bool             `protobuf:"varint,4,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	Language             *string           `protobuf:"bytes,5,opt,name=language,def=english" json:"language,omitempty"`
	Label                *string           `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	SkipChecksum         *bool             `protobuf:"varint,7,opt,name=skip_checksum,json=skipChecksum" json:"skip_checksum,omitempty"`
	XXX_unrecognized     []byte            `json:"-"`
}

func (m *LoadDevice) Reset()                    { *m = LoadDevice{} }
func (m *LoadDevice) String() string            { return proto.CompactTextString(m) }
func (*LoadDevice) ProtoMessage()               {}
func (*LoadDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

const Default_LoadDevice_Language string = "english"

func (m *LoadDevice) GetMnemonic() string {
	if m != nil && m.Mnemonic != nil {
		return *m.Mnemonic
	}
	return ""
}

func (m *LoadDevice) GetNode() *types.HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *LoadDevice) GetPin() string {
	if m != nil && m.Pin != nil {
		return *m.Pin
	}
	return ""
}

func (m *LoadDevice) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *LoadDevice) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_LoadDevice_Language
}

func (m *LoadDevice) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *LoadDevice) GetSkipChecksum() bool {
	if m != nil && m.SkipChecksum != nil {
		return *m.SkipChecksum
	}
	return false
}

// *
// Request: Ask device to do initialization involving user interaction
// @next EntropyRequest
// @next Failure
type ResetDevice struct {
	DisplayRandom        *bool   `protobuf:"varint,1,opt,name=display_random,json=displayRandom" json:"display_random,omitempty"`
	Strength             *uint32 `protobuf:"varint,2,opt,name=strength,def=256" json:"strength,omitempty"`
	PassphraseProtection *bool   `protobuf:"varint,3,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	PinProtection        *bool   `protobuf:"varint,4,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	Language             *string `protobuf:"bytes,5,opt,name=language,def=english" json:"language,omitempty"`
	Label                *string `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *ResetDevice) Reset()                    { *m = ResetDevice{} }
func (m *ResetDevice) String() string            { return proto.CompactTextString(m) }
func (*ResetDevice) ProtoMessage()               {}
func (*ResetDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

const Default_ResetDevice_Strength uint32 = 256
const Default_ResetDevice_Language string = "english"

func (m *ResetDevice) GetDisplayRandom() bool {
	if m != nil && m.DisplayRandom != nil {
		return *m.DisplayRandom
	}
	return false
}

func (m *ResetDevice) GetStrength() uint32 {
	if m != nil && m.Strength != nil {
		return *m.Strength
	}
	return Default_ResetDevice_Strength
}

func (m *ResetDevice) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *ResetDevice) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *ResetDevice) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_ResetDevice_Language
}

func (m *ResetDevice) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

// *
// Response: Ask for additional entropy from host computer
// @prev ResetDevice
// @next EntropyAck
type EntropyRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EntropyRequest) Reset()                    { *m = EntropyRequest{} }
func (m *EntropyRequest) String() string            { return proto.CompactTextString(m) }
func (*EntropyRequest) ProtoMessage()               {}
func (*EntropyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

// *
// Request: Provide additional entropy for seed generation function
// @prev EntropyRequest
// @next ButtonRequest
type EntropyAck struct {
	Entropy          []byte `protobuf:"bytes,1,opt,name=entropy" json:"entropy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EntropyAck) Reset()                    { *m = EntropyAck{} }
func (m *EntropyAck) String() string            { return proto.CompactTextString(m) }
func (*EntropyAck) ProtoMessage()               {}
func (*EntropyAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *EntropyAck) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

// *
// Request: Start recovery workflow asking user for specific words of mnemonic
// Used to recovery device safely even on untrusted computer.
// @next WordRequest
type RecoveryDevice struct {
	WordCount            *uint32 `protobuf:"varint,1,opt,name=word_count,json=wordCount" json:"word_count,omitempty"`
	PassphraseProtection *bool   `protobuf:"varint,2,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	PinProtection        *bool   `protobuf:"varint,3,opt,name=pin_protection,json=pinProtection" json:"pin_protection,omitempty"`
	Language             *string `protobuf:"bytes,4,opt,name=language,def=english" json:"language,omitempty"`
	Label                *string `protobuf:"bytes,5,opt,name=label" json:"label,omitempty"`
	EnforceWordlist      *bool   `protobuf:"varint,6,opt,name=enforce_wordlist,json=enforceWordlist" json:"enforce_wordlist,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *RecoveryDevice) Reset()                    { *m = RecoveryDevice{} }
func (m *RecoveryDevice) String() string            { return proto.CompactTextString(m) }
func (*RecoveryDevice) ProtoMessage()               {}
func (*RecoveryDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

const Default_RecoveryDevice_Language string = "english"

func (m *RecoveryDevice) GetWordCount() uint32 {
	if m != nil && m.WordCount != nil {
		return *m.WordCount
	}
	return 0
}

func (m *RecoveryDevice) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *RecoveryDevice) GetPinProtection() bool {
	if m != nil && m.PinProtection != nil {
		return *m.PinProtection
	}
	return false
}

func (m *RecoveryDevice) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return Default_RecoveryDevice_Language
}

func (m *RecoveryDevice) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *RecoveryDevice) GetEnforceWordlist() bool {
	if m != nil && m.EnforceWordlist != nil {
		return *m.EnforceWordlist
	}
	return false
}

// *
// Response: Device is waiting for user to enter word of the mnemonic
// Its position is shown only on device's internal display.
// @prev RecoveryDevice
// @prev WordAck
type WordRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *WordRequest) Reset()                    { *m = WordRequest{} }
func (m *WordRequest) String() string            { return proto.CompactTextString(m) }
func (*WordRequest) ProtoMessage()               {}
func (*WordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

// *
// Request: Computer replies with word from the mnemonic
// @prev WordRequest
// @next WordRequest
// @next Success
// @next Failure
type WordAck struct {
	Word             *string `protobuf:"bytes,1,req,name=word" json:"word,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WordAck) Reset()                    { *m = WordAck{} }
func (m *WordAck) String() string            { return proto.CompactTextString(m) }
func (*WordAck) ProtoMessage()               {}
func (*WordAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *WordAck) GetWord() string {
	if m != nil && m.Word != nil {
		return *m.Word
	}
	return ""
}

// *
// Request: Ask device to sign message
// @next MessageSignature
// @next Failure
type SignMessage struct {
	AddressN         []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Message          []byte   `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	CoinName         *string  `protobuf:"bytes,3,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SignMessage) Reset()                    { *m = SignMessage{} }
func (m *SignMessage) String() string            { return proto.CompactTextString(m) }
func (*SignMessage) ProtoMessage()               {}
func (*SignMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

const Default_SignMessage_CoinName string = "Bitcoin"

func (m *SignMessage) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *SignMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignMessage) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_SignMessage_CoinName
}

// *
// Request: Ask device to verify message
// @next Success
// @next Failure
type VerifyMessage struct {
	Address          *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Message          []byte  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VerifyMessage) Reset()                    { *m = VerifyMessage{} }
func (m *VerifyMessage) String() string            { return proto.CompactTextString(m) }
func (*VerifyMessage) ProtoMessage()               {}
func (*VerifyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *VerifyMessage) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *VerifyMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *VerifyMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// *
// Response: Signed message
// @prev SignMessage
type MessageSignature struct {
	Address          *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageSignature) Reset()                    { *m = MessageSignature{} }
func (m *MessageSignature) String() string            { return proto.CompactTextString(m) }
func (*MessageSignature) ProtoMessage()               {}
func (*MessageSignature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *MessageSignature) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *MessageSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// *
// Request: Ask device to encrypt message
// @next EncryptedMessage
// @next Failure
type EncryptMessage struct {
	Pubkey           []byte   `protobuf:"bytes,1,opt,name=pubkey" json:"pubkey,omitempty"`
	Message          []byte   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	DisplayOnly      *bool    `protobuf:"varint,3,opt,name=display_only,json=displayOnly" json:"display_only,omitempty"`
	AddressN         []uint32 `protobuf:"varint,4,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	CoinName         *string  `protobuf:"bytes,5,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EncryptMessage) Reset()                    { *m = EncryptMessage{} }
func (m *EncryptMessage) String() string            { return proto.CompactTextString(m) }
func (*EncryptMessage) ProtoMessage()               {}
func (*EncryptMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

const Default_EncryptMessage_CoinName string = "Bitcoin"

func (m *EncryptMessage) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *EncryptMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *EncryptMessage) GetDisplayOnly() bool {
	if m != nil && m.DisplayOnly != nil {
		return *m.DisplayOnly
	}
	return false
}

func (m *EncryptMessage) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *EncryptMessage) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_EncryptMessage_CoinName
}

// *
// Response: Encrypted message
// @prev EncryptMessage
type EncryptedMessage struct {
	Nonce            []byte `protobuf:"bytes,1,opt,name=nonce" json:"nonce,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Hmac             []byte `protobuf:"bytes,3,opt,name=hmac" json:"hmac,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EncryptedMessage) Reset()                    { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string            { return proto.CompactTextString(m) }
func (*EncryptedMessage) ProtoMessage()               {}
func (*EncryptedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *EncryptedMessage) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *EncryptedMessage) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

// *
// Request: Ask device to decrypt message
// @next Success
// @next Failure
type DecryptMessage struct {
	AddressN         []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Nonce            []byte   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Message          []byte   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Hmac             []byte   `protobuf:"bytes,4,opt,name=hmac" json:"hmac,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DecryptMessage) Reset()                    { *m = DecryptMessage{} }
func (m *DecryptMessage) String() string            { return proto.CompactTextString(m) }
func (*DecryptMessage) ProtoMessage()               {}
func (*DecryptMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *DecryptMessage) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *DecryptMessage) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *DecryptMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DecryptMessage) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

// *
// Response: Decrypted message
// @prev DecryptedMessage
type DecryptedMessage struct {
	Message          []byte  `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Address          *string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DecryptedMessage) Reset()                    { *m = DecryptedMessage{} }
func (m *DecryptedMessage) String() string            { return proto.CompactTextString(m) }
func (*DecryptedMessage) ProtoMessage()               {}
func (*DecryptedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *DecryptedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *DecryptedMessage) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

// *
// Request: Ask device to encrypt or decrypt value of given key
// @next CipheredKeyValue
// @next Failure
type CipherKeyValue struct {
	AddressN         []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Key              *string  `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value            []byte   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Encrypt          *bool    `protobuf:"varint,4,opt,name=encrypt" json:"encrypt,omitempty"`
	AskOnEncrypt     *bool    `protobuf:"varint,5,opt,name=ask_on_encrypt,json=askOnEncrypt" json:"ask_on_encrypt,omitempty"`
	AskOnDecrypt     *bool    `protobuf:"varint,6,opt,name=ask_on_decrypt,json=askOnDecrypt" json:"ask_on_decrypt,omitempty"`
	Iv               []byte   `protobuf:"bytes,7,opt,name=iv" json:"iv,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CipherKeyValue) Reset()                    { *m = CipherKeyValue{} }
func (m *CipherKeyValue) String() string            { return proto.CompactTextString(m) }
func (*CipherKeyValue) ProtoMessage()               {}
func (*CipherKeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *CipherKeyValue) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *CipherKeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CipherKeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CipherKeyValue) GetEncrypt() bool {
	if m != nil && m.Encrypt != nil {
		return *m.Encrypt
	}
	return false
}

func (m *CipherKeyValue) GetAskOnEncrypt() bool {
	if m != nil && m.AskOnEncrypt != nil {
		return *m.AskOnEncrypt
	}
	return false
}

func (m *CipherKeyValue) GetAskOnDecrypt() bool {
	if m != nil && m.AskOnDecrypt != nil {
		return *m.AskOnDecrypt
	}
	return false
}

func (m *CipherKeyValue) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

// *
// Response: Return ciphered/deciphered value
// @prev CipherKeyValue
type CipheredKeyValue struct {
	Value            []byte `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CipheredKeyValue) Reset()                    { *m = CipheredKeyValue{} }
func (m *CipheredKeyValue) String() string            { return proto.CompactTextString(m) }
func (*CipheredKeyValue) ProtoMessage()               {}
func (*CipheredKeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *CipheredKeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// *
// Request:  Estimated size of the transaction
// This behaves exactly like SignTx, which means that it can ask using TxRequest
// This call is non-blocking (except possible PassphraseRequest to unlock the seed)
// @next TxSize
// @next Failure
type EstimateTxSize struct {
	OutputsCount     *uint32 `protobuf:"varint,1,req,name=outputs_count,json=outputsCount" json:"outputs_count,omitempty"`
	InputsCount      *uint32 `protobuf:"varint,2,req,name=inputs_count,json=inputsCount" json:"inputs_count,omitempty"`
	CoinName         *string `protobuf:"bytes,3,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EstimateTxSize) Reset()                    { *m = EstimateTxSize{} }
func (m *EstimateTxSize) String() string            { return proto.CompactTextString(m) }
func (*EstimateTxSize) ProtoMessage()               {}
func (*EstimateTxSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

const Default_EstimateTxSize_CoinName string = "Bitcoin"

func (m *EstimateTxSize) GetOutputsCount() uint32 {
	if m != nil && m.OutputsCount != nil {
		return *m.OutputsCount
	}
	return 0
}

func (m *EstimateTxSize) GetInputsCount() uint32 {
	if m != nil && m.InputsCount != nil {
		return *m.InputsCount
	}
	return 0
}

func (m *EstimateTxSize) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_EstimateTxSize_CoinName
}

// *
// Response: Estimated size of the transaction
// @prev EstimateTxSize
type TxSize struct {
	TxSize           *uint32 `protobuf:"varint,1,opt,name=tx_size,json=txSize" json:"tx_size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxSize) Reset()                    { *m = TxSize{} }
func (m *TxSize) String() string            { return proto.CompactTextString(m) }
func (*TxSize) ProtoMessage()               {}
func (*TxSize) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *TxSize) GetTxSize() uint32 {
	if m != nil && m.TxSize != nil {
		return *m.TxSize
	}
	return 0
}

// *
// Request: Ask device to sign transaction
// @next PassphraseRequest
// @next PinMatrixRequest
// @next TxRequest
// @next Failure
type SignTx struct {
	OutputsCount     *uint32 `protobuf:"varint,1,req,name=outputs_count,json=outputsCount" json:"outputs_count,omitempty"`
	InputsCount      *uint32 `protobuf:"varint,2,req,name=inputs_count,json=inputsCount" json:"inputs_count,omitempty"`
	CoinName         *string `protobuf:"bytes,3,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	Version          *uint32 `protobuf:"varint,4,opt,name=version,def=1" json:"version,omitempty"`
	LockTime         *uint32 `protobuf:"varint,5,opt,name=lock_time,json=lockTime,def=0" json:"lock_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignTx) Reset()                    { *m = SignTx{} }
func (m *SignTx) String() string            { return proto.CompactTextString(m) }
func (*SignTx) ProtoMessage()               {}
func (*SignTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

const Default_SignTx_CoinName string = "Bitcoin"
const Default_SignTx_Version uint32 = 1
const Default_SignTx_LockTime uint32 = 0

func (m *SignTx) GetOutputsCount() uint32 {
	if m != nil && m.OutputsCount != nil {
		return *m.OutputsCount
	}
	return 0
}

func (m *SignTx) GetInputsCount() uint32 {
	if m != nil && m.InputsCount != nil {
		return *m.InputsCount
	}
	return 0
}

func (m *SignTx) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_SignTx_CoinName
}

func (m *SignTx) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_SignTx_Version
}

func (m *SignTx) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return Default_SignTx_LockTime
}

// *
// Request: Simplified transaction signing
// This method doesn't support streaming, so there are hardware limits in number of inputs and outputs.
// In case of success, the result is returned using TxRequest message.
// @next PassphraseRequest
// @next PinMatrixRequest
// @next TxRequest
// @next Failure
type SimpleSignTx struct {
	Inputs           []*types.TxInputType     `protobuf:"bytes,1,rep,name=inputs" json:"inputs,omitempty"`
	Outputs          []*types.TxOutputType    `protobuf:"bytes,2,rep,name=outputs" json:"outputs,omitempty"`
	Transactions     []*types.TransactionType `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
	CoinName         *string                  `protobuf:"bytes,4,opt,name=coin_name,json=coinName,def=Bitcoin" json:"coin_name,omitempty"`
	Version          *uint32                  `protobuf:"varint,5,opt,name=version,def=1" json:"version,omitempty"`
	LockTime         *uint32                  `protobuf:"varint,6,opt,name=lock_time,json=lockTime,def=0" json:"lock_time,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *SimpleSignTx) Reset()                    { *m = SimpleSignTx{} }
func (m *SimpleSignTx) String() string            { return proto.CompactTextString(m) }
func (*SimpleSignTx) ProtoMessage()               {}
func (*SimpleSignTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

const Default_SimpleSignTx_CoinName string = "Bitcoin"
const Default_SimpleSignTx_Version uint32 = 1
const Default_SimpleSignTx_LockTime uint32 = 0

func (m *SimpleSignTx) GetInputs() []*types.TxInputType {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *SimpleSignTx) GetOutputs() []*types.TxOutputType {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *SimpleSignTx) GetTransactions() []*types.TransactionType {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *SimpleSignTx) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return Default_SimpleSignTx_CoinName
}

func (m *SimpleSignTx) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_SimpleSignTx_Version
}

func (m *SimpleSignTx) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return Default_SimpleSignTx_LockTime
}

// *
// Response: Device asks for information for signing transaction or returns the last result
// If request_index is set, device awaits TxAck message (with fields filled in according to request_type)
// If signature_index is set, 'signature' contains signed input of signature_index's input
// @prev SignTx
// @prev SimpleSignTx
// @prev TxAck
type TxRequest struct {
	RequestType      *types.RequestType             `protobuf:"varint,1,opt,name=request_type,json=requestType,enum=RequestType" json:"request_type,omitempty"`
	Details          *types.TxRequestDetailsType    `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	Serialized       *types.TxRequestSerializedType `protobuf:"bytes,3,opt,name=serialized" json:"serialized,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *TxRequest) Reset()                    { *m = TxRequest{} }
func (m *TxRequest) String() string            { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()               {}
func (*TxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *TxRequest) GetRequestType() types.RequestType {
	if m != nil && m.RequestType != nil {
		return *m.RequestType
	}
	return types.RequestType_TXINPUT
}

func (m *TxRequest) GetDetails() *types.TxRequestDetailsType {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *TxRequest) GetSerialized() *types.TxRequestSerializedType {
	if m != nil {
		return m.Serialized
	}
	return nil
}

// *
// Request: Reported transaction data
// @prev TxRequest
// @next TxRequest
type TxAck struct {
	Tx               *types.TransactionType `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *TxAck) Reset()                    { *m = TxAck{} }
func (m *TxAck) String() string            { return proto.CompactTextString(m) }
func (*TxAck) ProtoMessage()               {}
func (*TxAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *TxAck) GetTx() *types.TransactionType {
	if m != nil {
		return m.Tx
	}
	return nil
}

// *
// Request: Ask device to sign identity
// @next SignedIdentity
// @next Failure
type SignIdentity struct {
	Identity         *types.IdentityType `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	ChallengeHidden  []byte              `protobuf:"bytes,2,opt,name=challenge_hidden,json=challengeHidden" json:"challenge_hidden,omitempty"`
	ChallengeVisual  *string             `protobuf:"bytes,3,opt,name=challenge_visual,json=challengeVisual" json:"challenge_visual,omitempty"`
	EcdsaCurveName   *string             `protobuf:"bytes,4,opt,name=ecdsa_curve_name,json=ecdsaCurveName" json:"ecdsa_curve_name,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *SignIdentity) Reset()                    { *m = SignIdentity{} }
func (m *SignIdentity) String() string            { return proto.CompactTextString(m) }
func (*SignIdentity) ProtoMessage()               {}
func (*SignIdentity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *SignIdentity) GetIdentity() *types.IdentityType {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *SignIdentity) GetChallengeHidden() []byte {
	if m != nil {
		return m.ChallengeHidden
	}
	return nil
}

func (m *SignIdentity) GetChallengeVisual() string {
	if m != nil && m.ChallengeVisual != nil {
		return *m.ChallengeVisual
	}
	return ""
}

func (m *SignIdentity) GetEcdsaCurveName() string {
	if m != nil && m.EcdsaCurveName != nil {
		return *m.EcdsaCurveName
	}
	return ""
}

// *
// Response: Device provides signed identity
// @prev SignIdentity
type SignedIdentity struct {
	Address          *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	Signature        []byte  `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignedIdentity) Reset()                    { *m = SignedIdentity{} }
func (m *SignedIdentity) String() string            { return proto.CompactTextString(m) }
func (*SignedIdentity) ProtoMessage()               {}
func (*SignedIdentity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *SignedIdentity) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *SignedIdentity) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SignedIdentity) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// *
// Request: Ask device to erase its firmware
// @next Success
// @next Failure
type FirmwareErase struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FirmwareErase) Reset()                    { *m = FirmwareErase{} }
func (m *FirmwareErase) String() string            { return proto.CompactTextString(m) }
func (*FirmwareErase) ProtoMessage()               {}
func (*FirmwareErase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

// *
// Request: Send firmware in binary form to the device
// @next Success
// @next Failure
type FirmwareUpload struct {
	Payload          []byte `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FirmwareUpload) Reset()                    { *m = FirmwareUpload{} }
func (m *FirmwareUpload) String() string            { return proto.CompactTextString(m) }
func (*FirmwareUpload) ProtoMessage()               {}
func (*FirmwareUpload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *FirmwareUpload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// *
// Request: "Press" the button on the device
// @next Success
type DebugLinkDecision struct {
	YesNo            *bool  `protobuf:"varint,1,req,name=yes_no,json=yesNo" json:"yes_no,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DebugLinkDecision) Reset()                    { *m = DebugLinkDecision{} }
func (m *DebugLinkDecision) String() string            { return proto.CompactTextString(m) }
func (*DebugLinkDecision) ProtoMessage()               {}
func (*DebugLinkDecision) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *DebugLinkDecision) GetYesNo() bool {
	if m != nil && m.YesNo != nil {
		return *m.YesNo
	}
	return false
}

// *
// Request: Computer asks for device state
// @next DebugLinkState
type DebugLinkGetState struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DebugLinkGetState) Reset()                    { *m = DebugLinkGetState{} }
func (m *DebugLinkGetState) String() string            { return proto.CompactTextString(m) }
func (*DebugLinkGetState) ProtoMessage()               {}
func (*DebugLinkGetState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

// *
// Response: Device current state
// @prev DebugLinkGetState
type DebugLinkState struct {
	Layout               []byte            `protobuf:"bytes,1,opt,name=layout" json:"layout,omitempty"`
	Pin                  *string           `protobuf:"bytes,2,opt,name=pin" json:"pin,omitempty"`
	Matrix               *string           `protobuf:"bytes,3,opt,name=matrix" json:"matrix,omitempty"`
	Mnemonic             *string           `protobuf:"bytes,4,opt,name=mnemonic" json:"mnemonic,omitempty"`
	Node                 *types.HDNodeType `protobuf:"bytes,5,opt,name=node" json:"node,omitempty"`
	PassphraseProtection *bool             `protobuf:"varint,6,opt,name=passphrase_protection,json=passphraseProtection" json:"passphrase_protection,omitempty"`
	ResetWord            *string           `protobuf:"bytes,7,opt,name=reset_word,json=resetWord" json:"reset_word,omitempty"`
	ResetEntropy         []byte            `protobuf:"bytes,8,opt,name=reset_entropy,json=resetEntropy" json:"reset_entropy,omitempty"`
	RecoveryFakeWord     *string           `protobuf:"bytes,9,opt,name=recovery_fake_word,json=recoveryFakeWord" json:"recovery_fake_word,omitempty"`
	RecoveryWordPos      *uint32           `protobuf:"varint,10,opt,name=recovery_word_pos,json=recoveryWordPos" json:"recovery_word_pos,omitempty"`
	XXX_unrecognized     []byte            `json:"-"`
}

func (m *DebugLinkState) Reset()                    { *m = DebugLinkState{} }
func (m *DebugLinkState) String() string            { return proto.CompactTextString(m) }
func (*DebugLinkState) ProtoMessage()               {}
func (*DebugLinkState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *DebugLinkState) GetLayout() []byte {
	if m != nil {
		return m.Layout
	}
	return nil
}

func (m *DebugLinkState) GetPin() string {
	if m != nil && m.Pin != nil {
		return *m.Pin
	}
	return ""
}

func (m *DebugLinkState) GetMatrix() string {
	if m != nil && m.Matrix != nil {
		return *m.Matrix
	}
	return ""
}

func (m *DebugLinkState) GetMnemonic() string {
	if m != nil && m.Mnemonic != nil {
		return *m.Mnemonic
	}
	return ""
}

func (m *DebugLinkState) GetNode() *types.HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DebugLinkState) GetPassphraseProtection() bool {
	if m != nil && m.PassphraseProtection != nil {
		return *m.PassphraseProtection
	}
	return false
}

func (m *DebugLinkState) GetResetWord() string {
	if m != nil && m.ResetWord != nil {
		return *m.ResetWord
	}
	return ""
}

func (m *DebugLinkState) GetResetEntropy() []byte {
	if m != nil {
		return m.ResetEntropy
	}
	return nil
}

func (m *DebugLinkState) GetRecoveryFakeWord() string {
	if m != nil && m.RecoveryFakeWord != nil {
		return *m.RecoveryFakeWord
	}
	return ""
}

func (m *DebugLinkState) GetRecoveryWordPos() uint32 {
	if m != nil && m.RecoveryWordPos != nil {
		return *m.RecoveryWordPos
	}
	return 0
}

// *
// Request: Ask device to restart
type DebugLinkStop struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DebugLinkStop) Reset()                    { *m = DebugLinkStop{} }
func (m *DebugLinkStop) String() string            { return proto.CompactTextString(m) }
func (*DebugLinkStop) ProtoMessage()               {}
func (*DebugLinkStop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

// *
// Response: Device wants host to log event
type DebugLinkLog struct {
	Level            *uint32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Bucket           *string `protobuf:"bytes,2,opt,name=bucket" json:"bucket,omitempty"`
	Text             *string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DebugLinkLog) Reset()                    { *m = DebugLinkLog{} }
func (m *DebugLinkLog) String() string            { return proto.CompactTextString(m) }
func (*DebugLinkLog) ProtoMessage()               {}
func (*DebugLinkLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *DebugLinkLog) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *DebugLinkLog) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *DebugLinkLog) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Initialize)(nil), "Initialize")
	proto.RegisterType((*GetFeatures)(nil), "GetFeatures")
	proto.RegisterType((*Features)(nil), "Features")
	proto.RegisterType((*ClearSession)(nil), "ClearSession")
	proto.RegisterType((*ApplySettings)(nil), "ApplySettings")
	proto.RegisterType((*ChangePin)(nil), "ChangePin")
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*Success)(nil), "Success")
	proto.RegisterType((*Failure)(nil), "Failure")
	proto.RegisterType((*ButtonRequest)(nil), "ButtonRequest")
	proto.RegisterType((*ButtonAck)(nil), "ButtonAck")
	proto.RegisterType((*PinMatrixRequest)(nil), "PinMatrixRequest")
	proto.RegisterType((*PinMatrixAck)(nil), "PinMatrixAck")
	proto.RegisterType((*Cancel)(nil), "Cancel")
	proto.RegisterType((*PassphraseRequest)(nil), "PassphraseRequest")
	proto.RegisterType((*PassphraseAck)(nil), "PassphraseAck")
	proto.RegisterType((*GetEntropy)(nil), "GetEntropy")
	proto.RegisterType((*Entropy)(nil), "Entropy")
	proto.RegisterType((*GetPublicKey)(nil), "GetPublicKey")
	proto.RegisterType((*PublicKey)(nil), "PublicKey")
	proto.RegisterType((*GetAddress)(nil), "GetAddress")
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*WipeDevice)(nil), "WipeDevice")
	proto.RegisterType((*LoadDevice)(nil), "LoadDevice")
	proto.RegisterType((*ResetDevice)(nil), "ResetDevice")
	proto.RegisterType((*EntropyRequest)(nil), "EntropyRequest")
	proto.RegisterType((*EntropyAck)(nil), "EntropyAck")
	proto.RegisterType((*RecoveryDevice)(nil), "RecoveryDevice")
	proto.RegisterType((*WordRequest)(nil), "WordRequest")
	proto.RegisterType((*WordAck)(nil), "WordAck")
	proto.RegisterType((*SignMessage)(nil), "SignMessage")
	proto.RegisterType((*VerifyMessage)(nil), "VerifyMessage")
	proto.RegisterType((*MessageSignature)(nil), "MessageSignature")
	proto.RegisterType((*EncryptMessage)(nil), "EncryptMessage")
	proto.RegisterType((*EncryptedMessage)(nil), "EncryptedMessage")
	proto.RegisterType((*DecryptMessage)(nil), "DecryptMessage")
	proto.RegisterType((*DecryptedMessage)(nil), "DecryptedMessage")
	proto.RegisterType((*CipherKeyValue)(nil), "CipherKeyValue")
	proto.RegisterType((*CipheredKeyValue)(nil), "CipheredKeyValue")
	proto.RegisterType((*EstimateTxSize)(nil), "EstimateTxSize")
	proto.RegisterType((*TxSize)(nil), "TxSize")
	proto.RegisterType((*SignTx)(nil), "SignTx")
	proto.RegisterType((*SimpleSignTx)(nil), "SimpleSignTx")
	proto.RegisterType((*TxRequest)(nil), "TxRequest")
	proto.RegisterType((*TxAck)(nil), "TxAck")
	proto.RegisterType((*SignIdentity)(nil), "SignIdentity")
	proto.RegisterType((*SignedIdentity)(nil), "SignedIdentity")
	proto.RegisterType((*FirmwareErase)(nil), "FirmwareErase")
	proto.RegisterType((*FirmwareUpload)(nil), "FirmwareUpload")
	proto.RegisterType((*DebugLinkDecision)(nil), "DebugLinkDecision")
	proto.RegisterType((*DebugLinkGetState)(nil), "DebugLinkGetState")
	proto.RegisterType((*DebugLinkState)(nil), "DebugLinkState")
	proto.RegisterType((*DebugLinkStop)(nil), "DebugLinkStop")
	proto.RegisterType((*DebugLinkLog)(nil), "DebugLinkLog")
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 2519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x59, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x0e, 0x1f, 0xa2, 0xc8, 0x26, 0x48, 0x8d, 0xb0, 0xd6, 0x9a, 0x96, 0x5f, 0x32, 0xec, 0xf8,
	0xb5, 0x1b, 0xda, 0xeb, 0x5d, 0x6f, 0x52, 0xae, 0x4a, 0x55, 0x6c, 0xc9, 0x8e, 0x9d, 0xf5, 0x43,
	0x05, 0x29, 0xde, 0x23, 0x0b, 0x02, 0xc7, 0x24, 0x56, 0x24, 0x80, 0x05, 0x40, 0x59, 0xdc, 0x43,
	0x8e, 0xa9, 0x1c, 0x73, 0xcc, 0x31, 0xb7, 0x6c, 0xce, 0xa9, 0x1c, 0xf2, 0x1b, 0x72, 0xce, 0x1f,
	0xc8, 0x39, 0x87, 0xe4, 0x92, 0x73, 0x7a, 0x66, 0x1a, 0xe0, 0x00, 0x02, 0x65, 0xaf, 0x0f, 0xb9,
	0xa8, 0x30, 0x5f, 0x37, 0x7b, 0x7a, 0xba, 0x7b, 0xfa, 0x31, 0x82, 0xee, 0x94, 0xc7, 0xb1, 0x33,
	0xe2, 0x71, 0x3f, 0x8c, 0x82, 0x24, 0xd8, 0x6c, 0x27, 0xf3, 0x30, 0x5d, 0x58, 0x06, 0xc0, 0x33,
	0xdf, 0x4b, 0x3c, 0x67, 0xe2, 0x7d, 0xc7, 0xad, 0x0e, 0xb4, 0x7f, 0xc9, 0x93, 0x27, 0xdc, 0x49,
	0x66, 0x11, 0x8f, 0xad, 0x7f, 0xd4, 0xa1, 0x99, 0x2e, 0xcc, 0x8f, 0xa1, 0x71, 0xc4, 0xfd, 0x61,
	0x10, 0xf5, 0x2a, 0x5b, 0x95, 0x9b, 0x2d, 0x9b, 0x56, 0xe6, 0x55, 0xe8, 0x4c, 0x9d, 0x6f, 0x82,
	0x68, 0x70, 0xc4, 0xa3, 0xd8, 0x0b, 0xfc, 0x5e, 0x15, 0xc9, 0x1d, 0xdb, 0x90, 0xe0, 0x6b, 0x85,
	0x49, 0x26, 0xcf, 0xd7, 0x98, 0x6a, 0xc4, 0x24, 0x40, 0x8d, 0x29, 0x74, 0x12, 0x77, 0x9c, 0x31,
	0xd5, 0x15, 0x93, 0x04, 0x53, 0xa6, 0x1b, 0xb0, 0x76, 0x10, 0x04, 0xc9, 0x24, 0x70, 0x86, 0x3c,
	0x1a, 0x4c, 0x83, 0x21, 0xef, 0xad, 0x20, 0x5b, 0xd3, 0xee, 0x2e, 0xe0, 0x17, 0x88, 0x9a, 0xe7,
	0xa1, 0x35, 0xe4, 0x47, 0x9e, 0xcb, 0x07, 0xde, 0xb0, 0xd7, 0x90, 0x2a, 0x37, 0x15, 0xf0, 0x6c,
	0x68, 0xfe, 0x18, 0xba, 0xa1, 0xe7, 0x0f, 0x84, 0x0d, 0xb8, 0x9b, 0x88, 0xbd, 0x56, 0xa5, 0x90,
	0x0e, 0xa2, 0xbb, 0x19, 0x68, 0x7e, 0x0e, 0x1b, 0xa1, 0x13, 0xc7, 0xe1, 0x38, 0x72, 0x62, 0xae,
	0x73, 0x37, 0x25, 0xf7, 0x99, 0x05, 0x51, 0xfb, 0xd1, 0x26, 0x34, 0x27, 0x8e, 0x3f, 0x9a, 0xa1,
	0xc9, 0x7b, 0x2d, 0xb5, 0x6f, 0xba, 0x36, 0xcf, 0xc0, 0xca, 0xc4, 0x39, 0xe0, 0x93, 0x1e, 0x48,
	0x82, 0x5a, 0x98, 0x97, 0x61, 0xc5, 0x0d, 0x3c, 0x3f, 0xee, 0xb5, 0xb7, 0x6a, 0x37, 0xdb, 0xf7,
	0x5a, 0xfd, 0x6d, 0x5c, 0xed, 0xa3, 0x97, 0x6c, 0x85, 0x9b, 0x5b, 0xd0, 0xf6, 0x32, 0x2f, 0x0d,
	0x7b, 0x86, 0xdc, 0x5d, 0x87, 0xc4, 0xa6, 0x11, 0x1e, 0x4e, 0x9a, 0xad, 0x83, 0x64, 0xc3, 0xce,
	0xd6, 0x05, 0x93, 0x8d, 0x9d, 0x78, 0xdc, 0xeb, 0x4a, 0x16, 0xcd, 0x64, 0x4f, 0x11, 0x15, 0x42,
	0xbc, 0x69, 0x18, 0x44, 0x09, 0xee, 0xb1, 0x26, 0xf7, 0xc8, 0xd6, 0xe6, 0x45, 0x00, 0x61, 0x31,
	0xd7, 0x71, 0xc7, 0x48, 0x65, 0x92, 0xda, 0x42, 0x64, 0x5b, 0x02, 0xe6, 0x27, 0xb0, 0xae, 0x59,
	0x8a, 0xb8, 0xd6, 0x25, 0x17, 0x5b, 0x10, 0x14, 0xb3, 0xd5, 0x05, 0x63, 0x7b, 0xc2, 0x9d, 0x68,
	0x0f, 0x03, 0x13, 0x15, 0xb4, 0x7e, 0x57, 0x81, 0xce, 0xc3, 0x30, 0x9c, 0xcc, 0xf7, 0x78, 0x92,
	0x78, 0xfe, 0x28, 0xce, 0xd9, 0xb0, 0xb2, 0xcc, 0x86, 0x55, 0xdd, 0x86, 0xe8, 0xd1, 0x99, 0xf0,
	0x51, 0xb6, 0x97, 0x0c, 0x31, 0xf4, 0x28, 0xa2, 0xbb, 0x19, 0x68, 0x5e, 0x02, 0x18, 0x07, 0x78,
	0x21, 0xdc, 0x88, 0x73, 0x15, 0x60, 0x86, 0xad, 0x21, 0xd6, 0x55, 0x68, 0x6d, 0x8f, 0x71, 0x27,
	0xbe, 0xeb, 0xf9, 0x22, 0xe4, 0x23, 0x3e, 0x0d, 0x8e, 0x94, 0x0e, 0x4d, 0x9b, 0x56, 0xd6, 0x9f,
	0x2b, 0x50, 0x47, 0xfa, 0xc8, 0xec, 0xc1, 0x2a, 0x5d, 0x2e, 0xd2, 0x32, 0x5d, 0x0a, 0x7b, 0x1c,
	0xcc, 0x92, 0x24, 0xc8, 0xc5, 0x58, 0x55, 0xd9, 0x43, 0x11, 0xb4, 0x88, 0x39, 0x19, 0x8d, 0xb5,
	0x1f, 0x14, 0x8d, 0xf5, 0xe5, 0xd1, 0x88, 0x07, 0x5a, 0xdd, 0x9b, 0xb9, 0x2e, 0xaa, 0xb5, 0x5c,
	0x5b, 0xeb, 0x31, 0xac, 0x3e, 0x71, 0xbc, 0x09, 0xde, 0x73, 0x0c, 0xb5, 0xba, 0x2b, 0x2e, 0x95,
	0xe0, 0xe8, 0xde, 0x33, 0xfa, 0x84, 0xcb, 0x68, 0x94, 0x14, 0x5d, 0x4c, 0x35, 0x2f, 0xe6, 0x2b,
	0xe8, 0x3c, 0x92, 0x67, 0xb3, 0xf9, 0xb7, 0x33, 0x1e, 0x27, 0xe6, 0xf5, 0x9c, 0x30, 0xb3, 0x9f,
	0xa3, 0x6a, 0x22, 0x4d, 0xa8, 0x0f, 0x9d, 0xc4, 0x21, 0x79, 0xf2, 0xdb, 0x6a, 0x43, 0x4b, 0xb1,
	0x3f, 0x74, 0x0f, 0xad, 0x9f, 0x03, 0x43, 0x83, 0xbf, 0x70, 0x92, 0xc8, 0x3b, 0x4e, 0x85, 0xdf,
	0x82, 0xba, 0xc8, 0x64, 0x24, 0x7c, 0xa3, 0x5f, 0x64, 0x50, 0xf2, 0x05, 0x8b, 0xb5, 0x05, 0x46,
	0x46, 0x45, 0x71, 0x26, 0x83, 0x1a, 0x9a, 0x16, 0x7f, 0x59, 0xc5, 0xed, 0xc4, 0xa7, 0xd5, 0x84,
	0xc6, 0xb6, 0xe3, 0xbb, 0x7c, 0x62, 0x7d, 0x04, 0xeb, 0x8b, 0x78, 0x21, 0x51, 0xd6, 0x1d, 0xe8,
	0x2c, 0x40, 0x21, 0x01, 0xe3, 0x48, 0x0b, 0x35, 0x25, 0x48, 0x43, 0x70, 0x47, 0xc0, 0x4c, 0xfa,
	0xd8, 0x4f, 0xa2, 0x20, 0x9c, 0x8b, 0xf3, 0xc5, 0x78, 0x4d, 0x25, 0x5f, 0xc7, 0x96, 0xdf, 0xc2,
	0x31, 0x29, 0x19, 0x2d, 0xca, 0xd5, 0xa7, 0xe4, 0x30, 0xec, 0x74, 0x69, 0x1d, 0x83, 0x81, 0x62,
	0x76, 0x67, 0x07, 0x13, 0xcf, 0xfd, 0x8a, 0xcf, 0x45, 0x52, 0x73, 0x86, 0x43, 0x4c, 0xc7, 0xf1,
	0x40, 0xa8, 0x5f, 0x43, 0x69, 0x4d, 0x02, 0x5e, 0x9a, 0x37, 0x81, 0x71, 0x77, 0x18, 0x3b, 0x03,
	0x77, 0x16, 0x1d, 0xf1, 0x81, 0xef, 0x4c, 0x53, 0x0f, 0x75, 0x25, 0xbe, 0x2d, 0xe0, 0x97, 0x88,
	0x9a, 0x57, 0xc0, 0x88, 0xc7, 0xc1, 0xdb, 0xc1, 0xd0, 0x8b, 0xc3, 0x89, 0x33, 0xa7, 0x70, 0x6b,
	0x0b, 0x6c, 0x47, 0x41, 0xd6, 0x2f, 0xa0, 0xb5, 0xd8, 0xf6, 0x32, 0xd4, 0x7d, 0xe5, 0xc7, 0x2a,
	0xe6, 0xa7, 0x76, 0xff, 0xe9, 0xce, 0x4b, 0x5c, 0x2a, 0x03, 0xfb, 0xe4, 0xc0, 0xe3, 0x70, 0x76,
	0x90, 0x3a, 0x50, 0x7c, 0x8b, 0x5b, 0x22, 0x6c, 0xf0, 0x50, 0xa9, 0x77, 0xba, 0xea, 0xd7, 0xa0,
	0x25, 0x32, 0x9d, 0xa6, 0xf3, 0x83, 0xd5, 0x47, 0x5e, 0x22, 0x30, 0xbb, 0x29, 0xfe, 0xbe, 0xa7,
	0xda, 0xe6, 0x7d, 0x68, 0x4e, 0x67, 0x93, 0x04, 0x13, 0xdf, 0x48, 0x5e, 0x8b, 0xf6, 0xbd, 0x73,
	0xfd, 0x17, 0x04, 0xd8, 0x7c, 0xc8, 0xf9, 0x74, 0xcf, 0x8d, 0xbc, 0x50, 0x05, 0x47, 0xc6, 0x2a,
	0x9c, 0x91, 0xea, 0x89, 0xce, 0x20, 0xb5, 0xc8, 0xad, 0xe9, 0x52, 0xd4, 0xca, 0xaf, 0xbd, 0x90,
	0xef, 0xc8, 0x22, 0x62, 0xfd, 0x1b, 0x8f, 0xf7, 0x1c, 0x73, 0xa7, 0x5a, 0x8a, 0x8c, 0x35, 0xf5,
	0x31, 0x3d, 0xf8, 0x9e, 0x9b, 0x66, 0xac, 0x74, 0x9d, 0x99, 0xaf, 0x2a, 0x15, 0x2a, 0x31, 0x1f,
	0xc5, 0x63, 0x4d, 0xfe, 0x4e, 0x7c, 0x7e, 0xd0, 0x5d, 0xc7, 0x02, 0xba, 0xc8, 0x9a, 0x2b, 0xca,
	0x88, 0xdc, 0x1f, 0x4d, 0xbc, 0x78, 0x5c, 0x96, 0x3e, 0x1b, 0x7a, 0xfa, 0xc4, 0xda, 0x1b, 0x1f,
	0x7a, 0xe1, 0x00, 0xf3, 0xb3, 0x7b, 0x18, 0xcf, 0xa6, 0x54, 0x0f, 0x0d, 0x01, 0x6e, 0x13, 0x66,
	0xfd, 0xab, 0x02, 0x6d, 0x9b, 0xc7, 0x3c, 0xa1, 0x33, 0x63, 0xde, 0x22, 0x57, 0x0c, 0x22, 0x07,
	0x9b, 0x81, 0x29, 0xe5, 0xc9, 0x0e, 0xa1, 0xb6, 0x04, 0xf1, 0xf8, 0xcd, 0x38, 0x89, 0x50, 0x93,
	0x64, 0xac, 0x9a, 0x83, 0x07, 0xb5, 0x7b, 0xf7, 0xbf, 0xb4, 0x33, 0x70, 0xf9, 0x61, 0x6b, 0xa7,
	0x1c, 0xf6, 0x64, 0xd2, 0xac, 0x97, 0x25, 0xcd, 0x0f, 0xb7, 0x89, 0xc5, 0xa0, 0x4b, 0x37, 0x34,
	0x4d, 0x03, 0xd7, 0x01, 0x08, 0x11, 0x39, 0x20, 0x77, 0x6d, 0x2b, 0xfa, 0xb5, 0xfd, 0x4f, 0x05,
	0xba, 0x36, 0x77, 0xb1, 0x56, 0x44, 0x73, 0xb2, 0x15, 0xd6, 0xcf, 0xb7, 0x41, 0x34, 0x1c, 0xb8,
	0xc1, 0xcc, 0x4f, 0x24, 0x7f, 0xc7, 0x6e, 0x09, 0x64, 0x5b, 0x00, 0xcb, 0x4d, 0x50, 0xfd, 0x41,
	0x26, 0xa8, 0xbd, 0xcb, 0x04, 0xf5, 0x77, 0x9a, 0x60, 0x45, 0x0f, 0x8b, 0x5b, 0x98, 0x52, 0xfc,
	0x37, 0x41, 0x84, 0x5d, 0x94, 0xd0, 0x15, 0x7f, 0x93, 0x48, 0x1b, 0x35, 0xed, 0x35, 0xc2, 0xbf,
	0x26, 0x58, 0xf4, 0x8e, 0xe2, 0x3b, 0x35, 0xd5, 0x45, 0x58, 0x15, 0x4b, 0x61, 0x27, 0x4c, 0x0e,
	0xe2, 0xc7, 0x74, 0x9d, 0xe4, 0xb7, 0xf5, 0x0d, 0xb4, 0xf7, 0xbc, 0x91, 0xff, 0x82, 0xca, 0xe5,
	0xa9, 0xc9, 0x21, 0x57, 0x70, 0x64, 0x7a, 0x4c, 0xab, 0x6c, 0x2e, 0x6d, 0xd4, 0x96, 0xa4, 0x0d,
	0xcb, 0x81, 0x0e, 0x76, 0x8f, 0xde, 0x9b, 0x79, 0xba, 0x5b, 0xee, 0x8a, 0x57, 0xb4, 0x2b, 0x6e,
	0x5e, 0x80, 0x16, 0xa6, 0x03, 0x5f, 0xb6, 0xbc, 0xd2, 0xf4, 0x86, 0xbd, 0x00, 0x74, 0x45, 0x6a,
	0xca, 0xe1, 0x69, 0xe5, 0xfb, 0x15, 0x30, 0x12, 0xbe, 0xa7, 0x73, 0x7f, 0xc8, 0x2e, 0xd6, 0xf7,
	0x15, 0x11, 0x77, 0x6e, 0x34, 0x0f, 0x93, 0x54, 0x61, 0x6c, 0x44, 0x30, 0xa3, 0x1e, 0xf2, 0x34,
	0xd0, 0x68, 0x55, 0x2c, 0xc5, 0x9a, 0x65, 0x30, 0x55, 0xa6, 0x57, 0x33, 0xf0, 0x27, 0x59, 0xaa,
	0x24, 0xec, 0x15, 0x42, 0x79, 0x9b, 0xd7, 0x4f, 0x4b, 0xc8, 0x2b, 0xcb, 0x2c, 0xfb, 0x1a, 0x18,
	0x69, 0xca, 0x87, 0xa9, 0xae, 0x18, 0x48, 0x7e, 0x80, 0x95, 0x94, 0x54, 0x55, 0x8b, 0x53, 0x34,
	0xc5, 0xe8, 0x18, 0x4f, 0x1d, 0x97, 0x2c, 0x2a, 0xbf, 0xad, 0x6f, 0xa1, 0xbb, 0xc3, 0x73, 0x16,
	0x38, 0x35, 0x40, 0xb2, 0x2d, 0xab, 0x4b, 0xb6, 0xac, 0x95, 0x6f, 0x59, 0xd7, 0xb6, 0x7c, 0x02,
	0x8c, 0xb6, 0x5c, 0x1c, 0xa5, 0xd0, 0x30, 0x69, 0x12, 0x34, 0xdf, 0x56, 0x73, 0xbe, 0xb5, 0xfe,
	0x8e, 0xde, 0xdb, 0xf6, 0xc2, 0x31, 0x8f, 0xb0, 0x70, 0xbe, 0x76, 0x26, 0xb3, 0x77, 0xe8, 0x8e,
	0xa9, 0x5f, 0xf8, 0x55, 0x49, 0x11, 0x9f, 0xe2, 0x34, 0x47, 0xe2, 0x77, 0xa4, 0xb5, 0x5a, 0xa8,
	0x64, 0x23, 0xf5, 0xa3, 0x3c, 0x97, 0x2e, 0xd1, 0x55, 0x5d, 0x27, 0x3e, 0x44, 0x37, 0x0f, 0x52,
	0x06, 0x35, 0x10, 0x19, 0x88, 0xbe, 0xf2, 0x1f, 0x9f, 0xe0, 0x1a, 0xaa, 0x63, 0xd2, 0x3d, 0x56,
	0x5c, 0x74, 0x74, 0xb3, 0x0b, 0x55, 0xef, 0x48, 0xe6, 0x7e, 0xc3, 0xc6, 0x2f, 0x0b, 0x5b, 0x0a,
	0x75, 0x18, 0x3e, 0xcc, 0x8e, 0x93, 0xe9, 0x57, 0xd1, 0xf4, 0xb3, 0x7e, 0x83, 0x41, 0x1b, 0x27,
	0xde, 0xd4, 0x49, 0xf8, 0xfe, 0xf1, 0x1e, 0x36, 0x38, 0xa2, 0xa4, 0x04, 0xb3, 0x24, 0x9c, 0x25,
	0x71, 0x96, 0xf4, 0x44, 0xf7, 0x63, 0x10, 0xa8, 0xf2, 0x1e, 0xc6, 0xa9, 0xe7, 0x6b, 0x3c, 0x55,
	0xc9, 0xd3, 0x56, 0x98, 0x62, 0x79, 0xbf, 0x4b, 0x7e, 0x05, 0x1a, 0xb4, 0xef, 0x59, 0x58, 0x4d,
	0x8e, 0x07, 0xd4, 0x6f, 0x89, 0x34, 0xdb, 0x48, 0x24, 0xc1, 0xfa, 0x4b, 0x05, 0x1a, 0xe2, 0x7a,
	0xee, 0x1f, 0xff, 0x7f, 0x75, 0xc3, 0x00, 0x58, 0xcd, 0x8d, 0xb4, 0x0f, 0x2a, 0x9f, 0xd9, 0x29,
	0x82, 0x9d, 0x64, 0x6b, 0x12, 0xb8, 0x87, 0x03, 0xb4, 0x9d, 0xba, 0x69, 0x48, 0xbe, 0x8b, 0x89,
	0x19, 0xb1, 0x7d, 0x84, 0xac, 0xff, 0x56, 0xc0, 0xd8, 0xc3, 0x31, 0x6c, 0xc2, 0x49, 0xf7, 0x6b,
	0xd0, 0x50, 0x2a, 0xc8, 0x58, 0x6a, 0x63, 0x8f, 0xbe, 0x7f, 0xfc, 0x4c, 0x00, 0xb2, 0xa1, 0x20,
	0x1a, 0x0e, 0x7d, 0xab, 0x74, 0x18, 0xd4, 0x5b, 0xb0, 0x75, 0x90, 0xed, 0x95, 0x44, 0x24, 0x5f,
	0x4a, 0x35, 0xbf, 0x00, 0x23, 0xc1, 0xea, 0x1d, 0x3b, 0xb2, 0x58, 0xc4, 0x78, 0x0a, 0xc1, 0xcd,
	0xfa, 0xfb, 0x0b, 0x50, 0xfe, 0x20, 0xc7, 0x95, 0x3f, 0x78, 0xfd, 0x3d, 0x0e, 0xbe, 0x72, 0xfa,
	0xc1, 0x1b, 0x27, 0x0f, 0xfe, 0xa7, 0x0a, 0xb4, 0xf6, 0xb3, 0x6e, 0xff, 0x0e, 0x18, 0x91, 0xfa,
	0x1c, 0x68, 0x5d, 0xbf, 0xd1, 0xd7, 0x9b, 0xfd, 0x76, 0xb4, 0x58, 0xe0, 0x0f, 0x56, 0x87, 0x3c,
	0xc1, 0xe9, 0x25, 0xa6, 0xbe, 0x6b, 0xa3, 0x9f, 0x49, 0xdb, 0x51, 0x04, 0x65, 0x08, 0xe2, 0x32,
	0x7f, 0x06, 0x10, 0x63, 0x99, 0xa0, 0x19, 0xbb, 0x26, 0x7f, 0xd3, 0x5b, 0xfc, 0x66, 0x2f, 0xa3,
	0xc9, 0x9f, 0x69, 0xbc, 0xd6, 0x2d, 0x58, 0xd9, 0x97, 0x73, 0xc5, 0x16, 0x54, 0x93, 0x63, 0xa9,
	0x5a, 0x99, 0x05, 0x91, 0x66, 0xfd, 0x4d, 0x7a, 0x73, 0xe4, 0x3f, 0x1b, 0x62, 0xaf, 0xe0, 0x25,
	0x73, 0xac, 0xb0, 0x4d, 0x8f, 0xbe, 0xe9, 0x87, 0x9d, 0x7e, 0x4a, 0x54, 0x4d, 0xaa, 0xb7, 0x60,
	0x65, 0xee, 0xd8, 0x99, 0x4c, 0xb0, 0x78, 0xf3, 0xc1, 0xd8, 0x1b, 0x22, 0x4e, 0x19, 0x6f, 0x2d,
	0xc3, 0x9f, 0x4a, 0x38, 0xcf, 0x7a, 0xe4, 0xc5, 0x33, 0x67, 0x42, 0xdd, 0xe5, 0x82, 0xf5, 0xb5,
	0x84, 0x4b, 0xa7, 0x86, 0x7a, 0xd9, 0xd4, 0x60, 0x8d, 0xa0, 0x2b, 0x54, 0xe7, 0xc3, 0x4c, 0xf9,
	0xe5, 0x25, 0x4e, 0x3c, 0x17, 0xc8, 0xf1, 0x61, 0x90, 0x66, 0x37, 0xac, 0x71, 0x61, 0x36, 0x50,
	0xe4, 0x2a, 0x60, 0xad, 0x58, 0x01, 0xd7, 0xa0, 0xf3, 0xc4, 0x8b, 0xa6, 0x6f, 0x9d, 0x88, 0x3f,
	0x96, 0xd3, 0xd4, 0x6d, 0xe8, 0xa6, 0xc0, 0xaf, 0x43, 0xf1, 0x60, 0x21, 0x76, 0x0e, 0x9d, 0xb9,
	0xf8, 0x4c, 0x47, 0x26, 0x5a, 0x22, 0xef, 0xfa, 0x0e, 0x3f, 0x98, 0x8d, 0x9e, 0x7b, 0xfe, 0x21,
	0xa6, 0x35, 0xf5, 0x04, 0xb2, 0x01, 0x8d, 0x39, 0xc7, 0xf4, 0x1b, 0x48, 0xee, 0xa6, 0xbd, 0x82,
	0xab, 0x97, 0x81, 0x98, 0xf5, 0x32, 0x5e, 0x1c, 0x55, 0xf6, 0x12, 0xcc, 0x5e, 0xd6, 0x3f, 0xab,
	0xa2, 0xfa, 0x10, 0x2a, 0x21, 0x51, 0x7f, 0xb1, 0x6a, 0xe2, 0x8d, 0x49, 0xeb, 0xaf, 0x5a, 0xa5,
	0x7d, 0x7b, 0x75, 0xd1, 0xb7, 0x23, 0xe7, 0x54, 0x8e, 0x99, 0x64, 0x6e, 0x5a, 0xe5, 0xc6, 0x83,
	0xfa, 0x92, 0xf1, 0x60, 0x65, 0xd9, 0x78, 0xb0, 0xb4, 0x39, 0x6c, 0x9c, 0xd2, 0x1c, 0xa2, 0x07,
	0x22, 0xd1, 0xab, 0xcb, 0xc6, 0x4d, 0xa6, 0xf4, 0x96, 0xdd, 0x92, 0x88, 0xe8, 0xcb, 0x44, 0x06,
	0x54, 0xe4, 0xb4, 0x85, 0x6d, 0xca, 0x93, 0x19, 0x12, 0x4c, 0x07, 0xd3, 0x4f, 0xc1, 0x8c, 0xa8,
	0x8d, 0x1d, 0xbc, 0x71, 0x0e, 0x55, 0x13, 0x48, 0x8f, 0x5a, 0x2c, 0xa5, 0x3c, 0x41, 0x82, 0x14,
	0x89, 0x96, 0xcf, 0xb8, 0x65, 0xaf, 0x1b, 0x06, 0xb1, 0x7c, 0xe8, 0xea, 0xd8, 0x6b, 0x29, 0x41,
	0x30, 0xee, 0x06, 0xb1, 0x70, 0xb1, 0x66, 0xe3, 0x20, 0xb4, 0x76, 0xc1, 0xc8, 0x80, 0xe7, 0xc1,
	0x48, 0xf6, 0xa3, 0xfc, 0x08, 0xfb, 0x51, 0x95, 0xc3, 0xd5, 0x42, 0x98, 0xf7, 0x60, 0xe6, 0x1e,
	0xf2, 0x84, 0x6c, 0x4e, 0x2b, 0x51, 0xd1, 0x13, 0x7e, 0x9c, 0x90, 0xd1, 0xe5, 0xf7, 0xed, 0xdf,
	0xae, 0x41, 0x9b, 0x2a, 0xb9, 0x4c, 0x08, 0x5b, 0xf0, 0xb1, 0xb6, 0x1c, 0x2c, 0x9e, 0x3d, 0xd9,
	0x8f, 0x36, 0xeb, 0xbf, 0xff, 0x6b, 0xaf, 0x82, 0x4e, 0x62, 0x3a, 0x87, 0x78, 0xe2, 0x61, 0x15,
	0xa2, 0x5d, 0x84, 0x8f, 0x74, 0x1a, 0xbd, 0xa9, 0xb0, 0xea, 0x66, 0xfd, 0x0f, 0x25, 0x64, 0x7a,
	0x35, 0x61, 0x35, 0x22, 0x5f, 0x86, 0x0d, 0x9d, 0x9c, 0x3d, 0x31, 0xb1, 0x3a, 0x89, 0x2f, 0x28,
	0xb7, 0x98, 0x33, 0xd9, 0x0a, 0x71, 0x5c, 0x85, 0x73, 0xb9, 0x1d, 0xf4, 0x0b, 0xc2, 0x1a, 0xc4,
	0x74, 0x0d, 0x36, 0xcb, 0x98, 0xd4, 0xa5, 0x61, 0xab, 0xe5, 0x9b, 0x2d, 0x1e, 0x2a, 0x58, 0xab,
	0xfc, 0xb4, 0x29, 0x19, 0xe8, 0x38, 0x16, 0xf4, 0x0a, 0x02, 0xb2, 0xb7, 0x02, 0xd6, 0x26, 0x11,
	0x85, 0x23, 0x2f, 0x18, 0x0c, 0x12, 0x52, 0xd0, 0x62, 0x31, 0x4b, 0xb3, 0x0e, 0x89, 0xb8, 0x02,
	0x67, 0x75, 0x0e, 0x6d, 0xf4, 0x64, 0x5d, 0x62, 0xb9, 0x00, 0x66, 0xce, 0x2d, 0xb2, 0x44, 0xb2,
	0x35, 0xa2, 0x16, 0xf4, 0xd4, 0xcb, 0x28, 0x63, 0xc4, 0x73, 0x09, 0xce, 0xe4, 0x4c, 0x46, 0xef,
	0xdd, 0x6c, 0x9d, 0xd4, 0xbc, 0x0e, 0x17, 0x0a, 0x41, 0x91, 0x7b, 0x65, 0x62, 0x66, 0xb9, 0x4d,
	0xf4, 0xf7, 0x26, 0xf6, 0x51, 0xb9, 0xb6, 0xea, 0xc5, 0x89, 0x9d, 0x29, 0xb7, 0x58, 0x56, 0x79,
	0xd8, 0x06, 0x6d, 0x71, 0x1e, 0xd6, 0xf3, 0x0c, 0x42, 0xf6, 0xc7, 0xe5, 0xae, 0xcf, 0xf7, 0xa0,
	0xec, 0x6c, 0xb9, 0x45, 0xf4, 0x67, 0x58, 0xd6, 0x2b, 0x8f, 0xb4, 0xdc, 0xcb, 0x2c, 0x3b, 0x57,
	0xce, 0x94, 0x7b, 0xd9, 0x63, 0x9b, 0xe5, 0x61, 0x9f, 0xbd, 0xe7, 0xb1, 0xf3, 0x4b, 0x23, 0x91,
	0x9e, 0x61, 0xd8, 0xc5, 0xf2, 0x48, 0x4c, 0xc9, 0x97, 0x68, 0x87, 0xc2, 0xa9, 0xf3, 0xf3, 0x3a,
	0xbb, 0x5a, 0x1e, 0x6a, 0x8b, 0x19, 0x9e, 0x5d, 0x2b, 0x0f, 0x35, 0x6d, 0x36, 0x65, 0xd7, 0xcb,
	0x4f, 0x9c, 0x1b, 0x29, 0xd9, 0x0d, 0x62, 0x2a, 0x44, 0x4b, 0x71, 0x28, 0x64, 0x37, 0x49, 0xa3,
	0x1b, 0x70, 0x31, 0x17, 0x2d, 0xc5, 0x17, 0x47, 0x76, 0x8b, 0x18, 0x0b, 0xbb, 0xe6, 0x5e, 0x21,
	0xd9, 0xed, 0x72, 0xdf, 0xe7, 0x1b, 0x71, 0xf6, 0x49, 0x79, 0xf4, 0x11, 0xf5, 0xd3, 0x72, 0x4b,
	0xe6, 0x9f, 0x2f, 0xd8, 0x4f, 0xca, 0xed, 0xa4, 0x4d, 0xfc, 0xac, 0x5f, 0x9e, 0x0a, 0xe9, 0x15,
	0x80, 0xdd, 0x29, 0xb7, 0x50, 0x71, 0xbc, 0x60, 0x77, 0x97, 0x79, 0x56, 0x9f, 0x07, 0xd9, 0x67,
	0xe5, 0xd2, 0x8a, 0xd3, 0x28, 0xbb, 0x57, 0x2e, 0x2d, 0x3f, 0x5d, 0xb2, 0xcf, 0xcb, 0xa5, 0x15,
	0x07, 0x42, 0xf6, 0x45, 0xf9, 0x5d, 0xd7, 0x1b, 0x3a, 0x76, 0xbf, 0xdc, 0x27, 0xf9, 0xce, 0x89,
	0x7d, 0x49, 0x92, 0x0a, 0xf6, 0xd4, 0xfe, 0xfb, 0xc6, 0x7e, 0x4a, 0x82, 0x0a, 0xa1, 0x72, 0xa2,
	0xb9, 0x61, 0xc3, 0xcd, 0xfa, 0x1f, 0x4f, 0x63, 0x4c, 0x3b, 0x1b, 0xc6, 0x89, 0xf1, 0x84, 0x31,
	0xf4, 0x66, 0x87, 0xbd, 0xd9, 0xac, 0x7f, 0x5f, 0x12, 0x79, 0xb9, 0x72, 0xcd, 0x46, 0x24, 0xaa,
	0x60, 0x09, 0xbd, 0x84, 0xb3, 0xb1, 0x12, 0xf4, 0xe8, 0x2e, 0x5c, 0x76, 0x83, 0x69, 0x3f, 0x76,
	0x92, 0x20, 0x1e, 0x7b, 0x13, 0xe7, 0x20, 0xee, 0x27, 0x11, 0xff, 0x2e, 0x88, 0xd4, 0xff, 0x20,
	0x0f, 0x66, 0x6f, 0x1e, 0x75, 0xf6, 0x25, 0x40, 0xa2, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd4,
	0xa2, 0x19, 0xf0, 0xb3, 0x1c, 0x00, 0x00,
}
